### ISSUE TITLE
Import reads entire music collection

### ISSUE THREAD

**Issue by ukdtom** [mfeingol/PlexTools#5]
Could be wrong here by reading the code, but looks like target server is scanned for all tracks, in order to get all raitingKeys and titles?

If so, then maybe better, if the import tool digested the plex guid, and then did a lookup on that?
( If target server contains a lot of tracks, it could be slow )

Like this url:

`https://192-168-1-14.9618d30a8a2b49c08a7faffc064b4472.plex.direct:32400/library/all?type=10&guid=plex%3A%2F%2Ftrack%2F5d07d51f403c6402908996ad,plex%3A%2F%2Ftrack%2F5d07d51b403c640290895303&X-Plex-Product=PlexTools&X-Plex-Client-Identifier=MyMACAddress&X-Plex-Token=1234ABCD
`

In above, I search for two tracks, and the output is non server centric, and thus might be faster to move playlists between servers

Above url returns as below

```
<MediaContainer size="2" allowSync="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1645197512">
<Track ratingKey="19706" key="/library/metadata/19706" parentRatingKey="19705" grandparentRatingKey="19704" guid="plex://track/5d07d51f403c6402908996ad" parentGuid="plex://album/5d07c2d8403c640290914cf7" grandparentGuid="plex://artist/5d07bce8403c64029056b5a6" parentStudio="XL Recordings" type="track" title="Daydreamer" grandparentKey="/library/metadata/19704" parentKey="/library/metadata/19705" librarySectionTitle="Music" librarySectionID="8" librarySectionKey="/library/sections/8" grandparentTitle="Adele" parentTitle="19" summary="" index="1" parentIndex="1" ratingCount="537088" skipCount="1" lastViewedAt="1542919206" parentYear="2008" thumb="/library/metadata/19705/thumb/1651111831" art="/library/metadata/19704/art/1651797753" parentThumb="/library/metadata/19705/thumb/1651111831" grandparentThumb="/library/metadata/19704/thumb/1651797753" grandparentArt="/library/metadata/19704/art/1651797753" duration="220552" addedAt="1389233409" updatedAt="1650422467">
<Media id="26756" duration="220552" bitrate="128" audioChannels="2" audioCodec="mp3" container="mp3">
<Part id="26798" key="/library/parts/26798/1389233409/file.mp3" duration="220552" file="/share/CACHEDEV1_DATA/Audio/Home-CD/Adele/Adele - 19 (disc 1)/01 - Daydreamer.mp3" size="3529589" container="mp3"/>
</Media>
</Track>
<Track ratingKey="19709" key="/library/metadata/19709" parentRatingKey="19705" grandparentRatingKey="19704" guid="plex://track/5d07d51b403c640290895303" parentGuid="plex://album/5d07c2d8403c640290914cf7" grandparentGuid="plex://artist/5d07bce8403c64029056b5a6" parentStudio="XL Recordings" type="track" title="Cold Shoulder" grandparentKey="/library/metadata/19704" parentKey="/library/metadata/19705" librarySectionTitle="Music" librarySectionID="8" librarySectionKey="/library/sections/8" grandparentTitle="Adele" parentTitle="19" summary="" index="4" parentIndex="1" ratingCount="518357" parentYear="2008" thumb="/library/metadata/19705/thumb/1651111831" art="/library/metadata/19704/art/1651797753" parentThumb="/library/metadata/19705/thumb/1651111831" grandparentThumb="/library/metadata/19704/thumb/1651797753" grandparentArt="/library/metadata/19704/art/1651797753" duration="191896" addedAt="1389233404" updatedAt="1650422467">
<Media id="26759" duration="191896" bitrate="128" audioChannels="2" audioCodec="mp3" container="mp3">
<Part id="26801" key="/library/parts/26801/1389233404/file.mp3" duration="191896" file="/share/CACHEDEV1_DATA/Audio/Home-CD/Adele/Adele - 19 (disc 1)/04 - Cold Shoulder.mp3" size="3071094" container="mp3"/>
</Media>
</Track>
</MediaContainer>
```

**Comment by mfeingol** [comment]
The problem with guids is that they ended up being inconsistent between servers, or at least, inconsistent between scanners? My initial implementation of import just looked at guids, and I quickly found that wasn't enough because it wasn't matching half my tracks. So I had to fall back to slightly fuzzier detection mechanisms.

And yes, I decided reading in the entire library once and operating in memory vs. looking up each track was faster. My test case was a playlist of some 1200 tracks.

So I think all this is by design... but let me know if you have suggestions.

**Comment by ukdtom** [comment]
It's not the old guid, but a plex guid, so it should be identical on different servers.
I know for a fact it is for movies, shows and episodes, since that's what Discovery use...

I'll do some more testing, and report back

**Comment by ukdtom** [comment]
So, it depends on the version of the music library ( Agents )

If using `Plex Music` a track will show as: `guid="plex://track/5d07cdb0403c640290f48acf"`
Above is persistent across  PMS servers

If using `Last.fm` as the agent (Legacy) then the track shows `guid="com.plexapp.agents.lastfm://Aerosmith/Gems/-1/5?lang=en"` and is more or less useless

So we could, in the JSON, look at the guid, and if it starts with `plex:` then use that, or?

And did a search among a few of my fiends, and found that some tracks exists in multiple editions, so a simple search might not find the correct one usince a total export or title search, but the plex guid will do the job ;)

![image](https://user-images.githubusercontent.com/4699449/171402186-605cffd2-2169-46c1-aeb3-a2311c5b3cdf.png)

**Comment by mfeingol** [comment]
Like I said, my scenario was exporting favorites from one server to another. Half the guids mismatched with a different scheme. Unfortunately I can't remember which schemes they were, but there was no obvious translation between the two... So I think the fuzzy matches are required.
